name: Verification flow
on:
  push:
    branches:
      - master
      - github-runner
  pull_request:
    branches:
      - master
jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make all
      - run: |
          cat test-efm.log
          cat test-syntax.log
